import XCTest
@testable import KlondikePro

/// Verifies that SeededShuffle.shuffle() produces identical output to the
/// Java backend (SeededShuffle.java) and TypeScript web app (seededShuffle.ts).
///
/// All test vectors were generated by the Python reference solver
/// (ios-app/scripts/klondike_solver.py) which mirrors SeededShuffle.java
/// exactly (xorshift32 + Fisher-Yates).  They were cross-checked against
/// the production API response for seed 2029734459 (see API-Reference.md).
///
/// If ANY assertion fails the iOS engine produces a different deal than the
/// server → every server-side replay will be rejected with "Invalid move".
final class SeededShuffleTests: XCTestCase {

    // MARK: - Structural invariants

    func testLengthIs52() {
        for seed: Int64 in [1, 2, 1000, 999999, 2_000_000_000] {
            XCTAssertEqual(SeededShuffle.shuffle(seed: seed).count, 52,
                           "Seed \(seed) produced wrong card count")
        }
    }

    func testAllCardsPresent() {
        for seed: Int64 in [1, 2, 1000, 999999, 2_000_000_000] {
            let result = SeededShuffle.shuffle(seed: seed)
            XCTAssertEqual(Set(result), Set(1...52),
                           "Seed \(seed) is missing cards or has duplicates")
        }
    }

    func testDeterminism() {
        let seed: Int64 = 987654321
        XCTAssertEqual(SeededShuffle.shuffle(seed: seed),
                       SeededShuffle.shuffle(seed: seed),
                       "Same seed must always produce the same deck")
    }

    func testDifferentSeedsDifferentDecks() {
        XCTAssertNotEqual(SeededShuffle.shuffle(seed: 1),
                          SeededShuffle.shuffle(seed: 2))
    }

    // MARK: - Known-seed vectors (DEV-256)
    //
    // Generated by: python3 ios-app/scripts/klondike_solver.py
    // Format: deck[0], deck[1], deck[2]  (first three card IDs out of 52)
    //
    // Card ID encoding (matches Card.java / Card.swift):
    //   1-13  = Clubs    A-K
    //   14-26 = Diamonds A-K
    //   27-39 = Hearts   A-K
    //   40-52 = Spades   A-K

    /// Seed 1 → J♥, 10♠, 5♠  (IDs 37, 49, 44)
    func testSeed1() {
        let result = SeededShuffle.shuffle(seed: 1)
        XCTAssertEqual(result[0], 37)
        XCTAssertEqual(result[1], 49)
        XCTAssertEqual(result[2], 44)
        // Full deck:
        let expected = [37,49,44,19,48,4,26,30,1,35,28,6,52,13,10,46,31,41,
                        47,14,43,39,2,32,17,34,38,7,25,8,33,51,29,50,15,5,
                        27,36,24,3,9,45,11,42,16,21,23,18,40,12,20,22]
        XCTAssertEqual(result, expected)
    }

    /// Seed 2 → J♦, 2♠, K♥  (IDs 24, 41, 39)
    func testSeed2() {
        let result = SeededShuffle.shuffle(seed: 2)
        XCTAssertEqual(result[0], 24)
        XCTAssertEqual(result[1], 41)
        XCTAssertEqual(result[2], 39)
        let expected = [24,41,39,15,33,23,47,16,48,25,6,32,36,46,1,30,7,21,
                        45,52,34,14,8,44,28,42,31,20,50,3,22,51,38,18,17,12,
                        4,19,13,10,37,29,27,35,26,2,40,11,9,5,49,43]
        XCTAssertEqual(result, expected)
    }

    /// Seed 1000 → 4♠, 10♠, 6♥  (IDs 43, 49, 32)
    func testSeed1000() {
        let result = SeededShuffle.shuffle(seed: 1000)
        XCTAssertEqual(result[0], 43)
        XCTAssertEqual(result[1], 49)
        XCTAssertEqual(result[2], 32)
    }

    /// Seed 999999 → A♠, 3♥, 2♣  (IDs 40, 29, 2)
    func testSeed999999() {
        let result = SeededShuffle.shuffle(seed: 999999)
        XCTAssertEqual(result[0], 40)
        XCTAssertEqual(result[1], 29)
        XCTAssertEqual(result[2], 2)
    }

    /// Seed 2 000 000 000 → 7♣, 10♠, 6♠  (IDs 7, 49, 45)
    func testSeed2Billion() {
        let result = SeededShuffle.shuffle(seed: 2_000_000_000)
        XCTAssertEqual(result[0], 7)
        XCTAssertEqual(result[1], 49)
        XCTAssertEqual(result[2], 45)
    }

    /// Seed 2029734459 — taken from API-Reference.md example response.
    /// First 3 cards must be Q♣, 6♠, A♠  (IDs 12, 45, 40).
    func testKnownAPIReferenceSeed() {
        let seed: Int64 = 2029734459
        let result = SeededShuffle.shuffle(seed: seed)
        XCTAssertEqual(result[0], 12, "deck[0] should be Q♣")
        XCTAssertEqual(result[1], 45, "deck[1] should be 6♠")
        XCTAssertEqual(result[2], 40, "deck[2] should be A♠")
    }

    /// Seed boundary — minimum valid seed
    func testMinimumSeed() {
        let result = SeededShuffle.shuffle(seed: 1)
        XCTAssertEqual(result.count, 52)
    }

    /// Seed boundary — UInt32 max (4 294 967 295)
    func testMaxSeed() {
        let result = SeededShuffle.shuffle(seed: Int64(UInt32.max))
        XCTAssertEqual(result.count, 52)
        XCTAssertEqual(Set(result).count, 52)
    }
}

// MARK: - Game Engine Tests

final class GameEngineTests: XCTestCase {

    // MARK: - Initial deal structure

    func testInitialDeal() {
        let game = GameState(seed: 42, drawMode: "draw3")

        // 7 tableau columns
        XCTAssertEqual(game.tableau.count, 7)
        // Column i has (i+1) cards
        for i in 0..<7 {
            XCTAssertEqual(game.tableau[i].count, i + 1,
                           "Column \(i) should have \(i+1) cards")
        }
        // Only the top card of each column is face up
        for col in game.tableau {
            for (idx, card) in col.enumerated() {
                if idx == col.count - 1 {
                    XCTAssertTrue(card.isFaceUp, "Top card should be face up")
                } else {
                    XCTAssertFalse(card.isFaceUp, "Non-top card should be face down")
                }
            }
        }

        // Stock has 52 − (1+2+3+4+5+6+7) = 24 cards
        XCTAssertEqual(game.stock.count, 24)
        XCTAssertTrue(game.waste.isEmpty)
        XCTAssertTrue(game.foundation.allSatisfy { $0 == nil })
    }

    // MARK: - Draw mechanics

    func testDraw3() {
        var game = GameState(seed: 100, drawMode: "draw3")
        let stockBefore = game.stock.count
        game.draw()
        XCTAssertEqual(game.waste.count, 3)
        XCTAssertEqual(game.stock.count, stockBefore - 3)
        XCTAssertEqual(game.turns, "draw")
    }

    func testDraw1() {
        var game = GameState(seed: 100, drawMode: "draw1")
        game.draw()
        XCTAssertEqual(game.waste.count, 1)
        XCTAssertEqual(game.turns, "draw")
    }

    func testStockFlip() {
        // After exhausting stock, drawing again should flip waste back
        var game = GameState(seed: 100, drawMode: "draw1")
        let total = game.stock.count
        for _ in 0..<total { game.draw() }
        XCTAssertTrue(game.stock.isEmpty)
        XCTAssertEqual(game.waste.count, total)
        game.draw()  // flip
        XCTAssertTrue(game.waste.isEmpty)
        XCTAssertEqual(game.stock.count, total)
    }

    // MARK: - Undo

    func testUndo() {
        var game = GameState(seed: 100, drawMode: "draw3")
        game.draw()
        XCTAssertFalse(game.waste.isEmpty)
        game.undo()
        XCTAssertTrue(game.waste.isEmpty)
        XCTAssertEqual(game.turns, "")
    }

    // MARK: - Turns format

    func testTurnsFormat() {
        var game = GameState(seed: 100, drawMode: "draw3")
        game.draw()
        game.draw()
        XCTAssertEqual(game.turns, "draw,draw")
    }

    // MARK: - Win detection

    func testNotWonOnStart() {
        let game = GameState(seed: 42, drawMode: "draw3")
        XCTAssertFalse(game.isWon)
    }

    // MARK: - Known-win replay (DEV-257)
    //
    // The 563-token turns string was produced by the Python solver
    // (klondike_solver.py) which mirrors Java GameState.java exactly,
    // then verified by the Python replay() function.
    //
    // Seed 2, draw1 — first card drawn: J♦ (ID 24)
    //
    // This test proves:
    //   1. SeededShuffle.shuffle() matches the Java shuffle for seed 2
    //   2. GameState.replay() correctly applies all 563 moves
    //   3. isWon == true after replay
    //
    // If this test fails the Swift game engine diverges from the server
    // and submitted turns will be rejected as invalid.

    private let knownWinSeed: Int64 = 2
    private let knownWinTurns: String = {
        // 563 tokens, draw1 mode, seed 2
        // Produced by: python3 ios-app/scripts/klondike_solver.py
        // Verified: ✅ monte_carlo_solve() + verify_turns()
        [
            "tf:4","tt:4:3:5","draw","wt:3","tt:4:2:3","tt:4:1:5","tt:4:0:6","tt:1:1:4",
            "draw","draw","draw","wt:4","tt:0:0:4","tt:4:0:0","draw","tt:0:0:4",
            "draw","tt:4:0:0","wt:6","tt:0:0:4","draw","tt:4:0:0","draw","tt:0:0:4",
            "draw","tt:4:0:0","wt:6","tt:0:0:4","draw","tt:4:0:0","draw","tt:0:0:4",
            "wt:0","tt:3:3:0","tt:5:5:3","tt:3:2:0","tt:3:1:6","tt:6:6:3","tt:1:0:3","tt:4:0:1",
            "tt:5:4:4","tt:6:5:5","draw","wt:1","draw","draw","draw","wf",
            "draw","wt:1","tt:3:0:1","tt:0:0:3","tt:1:0:0","tt:4:0:1","tt:0:0:4","tt:3:0:0",
            "tt:1:0:3","tt:4:0:1","tt:0:0:4","tt:1:0:0","tt:4:0:1","tt:0:0:4","tt:3:0:0","tt:1:0:3",
            "tt:4:0:1","tt:3:0:4","tt:1:0:3","tt:4:0:1","tt:0:0:4","tt:1:0:0","tt:4:0:1","tt:0:0:4",
            "tt:3:0:0","draw","tt:0:0:3","tt:1:0:0","tt:3:0:1","tt:4:0:3","tt:0:0:4","tt:1:0:0",
            "tt:4:0:1","tt:0:0:4","tt:1:0:0","tt:3:0:1","tt:4:0:3","tt:0:0:4","tt:3:0:0","tt:4:0:3",
            "tt:0:0:4","tt:1:0:0","tt:3:0:1","tt:4:0:3","tt:1:0:4","tt:3:0:1","tt:4:0:3","tt:0:0:4",
            "tt:1:0:0","wt:1","draw","wf","draw","wf","tf:0","tf:6",
            "tf:6","wf","tt:6:2:4","draw","draw","wt:2","draw","draw",
            "draw","wf","tf:4","draw","draw","wf","draw","draw",
            "wt:3","draw","draw","wt:1","draw","draw","wt:1","draw",
            "wt:3","tt:2:2:3","tt:5:3:2","tt:2:1:6","tt:5:2:3","tt:5:1:3","tf:5","tf:6",
            "tf:6","tf:4","tf:4","tf:6","tf:4","tt:4:0:5","tt:0:0:4","tt:1:0:0",
            "tt:4:0:1","tt:5:0:4","tt:3:0:5","tt:4:0:3","tt:0:0:4","tt:3:0:0","tt:5:0:3","tt:4:0:5",
            "tt:0:0:4","tt:1:0:0","tt:4:0:1","tt:0:0:4","tt:5:0:0","tt:4:0:5","tt:1:0:4","tt:0:0:1",
            "tt:4:0:0","tt:1:0:4","tt:3:0:1","tt:5:0:3","tt:1:0:5","tt:0:0:1","tt:5:0:0","tt:1:0:5",
            "tt:4:0:1","tt:3:0:4","tt:5:0:3","tt:0:0:5","tt:1:0:0","tt:3:0:1","tt:0:0:3","tt:1:0:0",
            "tt:3:0:1","tt:5:0:3","tt:1:0:5","tt:3:0:1","tt:0:0:3","tt:4:0:0","tt:3:0:4","tt:0:0:3",
            "tt:1:0:0","tt:3:0:1","tt:4:0:3","tt:5:0:4","tt:1:0:5","tt:0:0:1","tt:5:0:0","tt:1:0:5",
            "tt:4:0:1","tt:5:0:4","tt:1:0:5","tt:3:0:1","tt:5:0:3","tt:1:0:5","tt:0:0:1","tt:3:0:0",
            "tt:1:0:3","tt:0:0:1","tt:3:0:0","wt:4","tt:4:0:3","tt:0:0:4","tt:1:0:0","tt:4:0:1",
            "tt:5:0:4","tt:1:0:5","tt:4:0:1","tt:3:0:4","tt:1:0:3","tt:5:0:1","tt:0:0:5","tt:4:0:0",
            "tt:5:0:4","tt:1:0:5","tt:4:0:1","tt:5:0:4","tt:1:0:5","tt:3:0:1","tt:4:0:3","tt:1:0:4",
            "tt:5:0:1","tt:4:0:5","tt:1:0:4","tt:5:0:1","tt:3:0:5","tt:4:0:3","tt:5:0:4","tt:1:0:5",
            "tt:3:0:1","draw","tt:4:0:3","tt:0:0:4","tt:5:0:0","tt:4:0:5","tt:3:0:4","tt:1:0:3",
            "tt:4:0:1","tt:5:0:4","tt:0:0:5","tt:3:0:0","tt:1:0:3","tt:4:0:1","tt:3:0:4","tt:5:0:3",
            "tt:4:0:5","tt:0:0:4","tt:3:0:0","tt:1:0:3","tt:0:0:1","tt:4:0:0","tt:3:0:4","tt:0:0:3",
            "tt:4:0:0","tt:5:0:4","tt:3:0:5","tt:4:0:3","tt:5:0:4","tt:3:0:5","tt:1:0:3","tt:5:0:1",
            "tt:3:0:5","tt:0:0:3","tt:5:0:0","tt:3:0:5","tt:0:0:3","tt:1:0:0","tt:3:0:1","tt:0:0:3",
            "tt:1:0:0","tt:5:0:1","tt:4:0:5","tt:1:0:4","tt:0:0:1","tt:3:0:0","tt:1:0:3","tt:0:0:1",
            "tt:4:0:0","tt:3:0:4","tt:0:0:3","tt:1:0:0","tt:4:0:1","tt:0:0:4","tt:1:0:0","tt:4:0:1",
            "tt:3:0:4","wt:4","tt:0:0:3","tt:1:0:0","tt:4:0:1","tt:0:0:4","tt:5:0:0","tt:3:0:5",
            "tt:0:0:3","tt:1:0:0","tt:5:0:1","tt:0:0:5","tt:4:0:0","tt:5:0:4","tt:1:0:5","tt:0:0:1",
            "tt:4:0:0","tt:3:0:4","tt:5:0:3","tt:4:0:5","tt:1:0:4","tt:3:0:1","tt:4:0:3","tt:1:0:4",
            "tt:3:0:1","tt:5:0:3","tt:1:0:5","tt:3:0:1","tt:0:0:3","tt:5:0:0","tt:4:0:5","tt:1:0:4",
            "tt:3:0:1","tt:5:0:3","tt:1:0:5","tt:4:0:1","tt:0:0:4","tt:5:0:0","tt:3:0:5","tt:0:0:3",
            "tt:5:0:0","tt:1:0:5","tt:0:0:1","tt:4:0:0","tt:1:0:4","tt:3:0:1","tt:0:0:3","tt:4:0:0",
            "tt:1:0:4","tt:0:0:1","tt:3:0:0","wt:4","tt:5:0:3","tt:0:0:5","tt:1:0:0","tt:4:0:1",
            "tt:5:0:4","tt:3:0:5","tt:0:0:3","tt:5:0:0","tt:4:0:5","tt:3:0:4","tt:0:0:3","tt:1:0:0",
            "tt:4:0:1","tt:3:0:4","tt:1:0:3","tt:0:0:1","tt:3:0:0","tt:1:0:3","tt:5:0:1","tt:3:0:5",
            "tt:4:0:3","tt:0:0:4","tt:3:0:0","tt:4:0:3","tt:0:0:4","tt:5:0:0","tt:4:0:5","tt:3:0:4",
            "tt:0:0:3","tt:1:0:0","tt:3:0:1","tt:0:0:3","tt:1:0:0","tt:4:0:1","tt:5:0:4","tt:1:0:5",
            "tt:4:0:1","tt:3:0:4","tt:5:0:3","tt:0:0:5","tt:4:0:0","tt:1:0:4","tt:5:0:1","tt:3:0:5",
            "tt:4:0:3","tt:0:0:4","tt:1:0:0","tt:4:0:1","tt:5:0:4","draw","tt:0:0:5","tt:3:0:0",
            "tt:4:0:3","tt:5:0:4","tt:0:0:5","tt:1:0:0","tt:5:0:1","tt:0:0:5","tt:4:0:0","tt:5:0:4",
            "tt:1:0:5","tt:3:0:1","tt:5:0:3","tt:4:0:5","tt:3:0:4","tt:0:0:3","tt:5:0:0","tt:1:0:5",
            "tt:3:0:1","tt:4:0:3","tt:1:0:4","tt:0:0:1","tt:5:0:0","tt:1:0:5","tt:4:0:1","tt:0:0:4",
            "tt:3:0:0","tt:1:0:3","tt:4:0:1","tt:3:0:4","tt:0:0:3","tt:5:0:0","tt:4:0:5","tt:0:0:4",
            "tt:3:0:0","tt:5:0:3","tt:1:0:5","tt:4:0:1","tt:5:0:4","tt:0:0:5","tt:3:0:0","tt:4:0:3",
            "tt:5:0:4","tt:0:0:5","tt:3:0:0","tt:1:0:3","tt:5:0:1","tt:4:0:5","tt:1:0:4","tt:3:0:1",
            "tt:4:0:3","tt:1:0:4","tt:3:0:1","tt:0:0:3","tt:4:0:0","tt:3:0:4","tt:1:0:3","tt:4:0:1",
            "tt:0:0:4","wt:5","tt:1:0:0","tt:3:0:1","tt:0:0:3","tt:4:0:0","tt:1:0:4","tt:3:0:1",
            "tt:5:0:3","tt:0:0:5","tt:1:0:0","tt:4:0:1","tt:5:0:4","tt:1:0:5","tt:3:0:1","tt:0:0:3",
            "tt:4:0:0","tt:1:0:4","tt:0:0:1","tt:3:0:0","tt:4:0:3","tt:0:0:4","tt:1:0:0","tt:4:0:1",
            "tt:3:0:4","tt:0:0:3","tt:1:0:0","tt:4:0:1","tt:0:0:4","tt:1:0:0","tt:4:0:1","tt:3:0:4",
            "tt:1:0:3","tt:4:0:1","tt:5:0:4","tt:1:0:5","tt:0:0:1","tt:4:0:0","tt:5:0:4","tt:1:0:5",
            "tt:4:0:1","tt:5:0:4","tt:3:0:5","tt:4:0:3","tt:5:0:4","tt:3:0:5","tt:0:0:3","tt:4:0:0",
            "tt:5:0:4","tt:1:0:5","tt:0:0:1","tt:3:0:0","tt:5:0:3","tt:4:0:5","tt:0:0:4","tt:1:0:0",
            "tt:4:0:1","tt:0:0:4","tt:3:0:0","tt:1:0:3","tt:5:0:1","tt:4:0:5","tt:3:0:4","tt:1:0:3",
            "tt:4:0:1","tt:3:0:4","tt:0:0:3","tt:4:0:0","tt:5:0:4","tt:3:0:5","tt:4:0:3","tt:0:0:4",
            "tt:5:0:0","wt:4","tt:1:0:5","tt:4:0:1","tt:0:0:4","tt:3:0:0","tt:1:0:3","tt:4:0:1",
            "tt:6:1:3","tf:6","tf:2","tf:1","tf:5","tf:1","tf:5","tf:1",
            "tf:5","tf:1","tf:1","tf:1","tf:1","tf:0","tf:5","tf:0",
            "tf:3","tf:5","tf:5","tf:1","tf:3","tf:5","tf:1","tf:5",
            "tf:3","tf:0","tf:1","tf:0","tf:3","tf:3","tf:0","tf:5",
            "tf:1","tf:5","tf:3"
        ].joined(separator: ",")
    }()

    func testKnownWin() {
        // DEV-257: replay a Python-verified winning sequence in the Swift engine.
        var game = GameState(seed: knownWinSeed, drawMode: "draw1")
        let success = game.replay(turns: knownWinTurns)
        XCTAssertTrue(success,   "replay() returned false — a move was rejected")
        XCTAssertTrue(game.isWon, "Game should be won after replaying all turns")
        XCTAssertEqual(game.moveCount, 563)
    }

    // MARK: - E2E turn submission (DEV-258)

    /// Submits the pre-verified turns string for seed 2 to the live API.
    ///
    /// Pre-conditions:
    ///   1. API must be reachable (skipped if offline).
    ///   2. A hand must exist on the server for seed 2.
    ///      Because POST /api/v1/hands uses random seeds, this test creates
    ///      a new hand and skips if the returned seed ≠ 2.
    ///      (In practice, a future HandController test endpoint will allow
    ///      seeding — tracked as DEV-261.)
    func testE2ECompleteSession() async throws {
        let reachable = (try? await APIClient.shared.healthCheck()) ?? false
        guard reachable else {
            throw XCTSkip("API unreachable — skipping E2E session test")
        }

        // Create a fresh session (random seed)
        struct HandRequest: Encodable { let drawMode: String }
        struct HandResponse: Decodable { let uuid: String; let seed: Int64; let drawMode: String }

        guard let hand: HandResponse =
                try? await APIClient.shared.post("/api/v1/hands",
                                                  body: HandRequest(drawMode: "draw1"))
        else {
            throw XCTSkip("Could not create hand — skipping E2E test")
        }

        guard hand.seed == knownWinSeed else {
            throw XCTSkip("Created hand has seed \(hand.seed), not \(knownWinSeed) — skipping (DEV-261 needed for deterministic test seed)")
        }

        // Create a session for that hand
        struct SessionRequest: Encodable { let handUuid: String }
        struct SessionResponse: Decodable { let uuid: String }

        guard let session: SessionResponse =
                try? await APIClient.shared.post("/api/v1/sessions",
                                                  body: SessionRequest(handUuid: hand.uuid))
        else {
            throw XCTSkip("Could not create session — skipping E2E test")
        }

        // Submit the verified winning turns
        struct CompleteRequest: Encodable { let moves: Int; let timeSeconds: Int; let turns: String }
        struct CompleteResponse: Decodable { let uuid: String; let completed: Bool }

        let req = CompleteRequest(moves: 563, timeSeconds: 0, turns: knownWinTurns)
        guard let result: CompleteResponse =
                try? await APIClient.shared.post(
                    "/api/v1/sessions/\(session.uuid)/complete", body: req)
        else {
            XCTFail("POST /api/v1/sessions/\(session.uuid)/complete failed")
            return
        }

        XCTAssertTrue(result.completed, "Session should be marked completed after valid turns")
    }
}
